site_name: EventBus
theme: material
pages:
  - Home: index.md
  - Installation: installation.md
  - QuickStart: quickstart.md
  - Development: development.md
  - Configuration: configuration.md
  - Deployment: deployment.md
