site_name: EventBus
theme: material
pages:
  - Welcome: index.md
  - Installation: installation.md
  - QuickStart: quickstart.md
  - Concepts: concepts.md
  - Components: components.md
  - Data Format: data_format.md
  - Deployment: deployment.md
  - Admin Interface: admin_interface.md
  - Monitoring: monitoring.md
