site_name: EventBus
theme: material
pages:
  - Home: index.md
  - Installation: installation.md
  - QuickStart: quickstart.md
  - Components: components.md
  - Unified Event: unified_event.md
  - Configuration: configuration.md
  - Deployment: deployment.md
