---
- name: clone or update repository
  become_user: "{{ daemon_user }}"
  git:
    repo=https://github.com/thenetcircle/event-bus.git
    dest={{ eventbus_home }}
    version={{ eventbus_version | default("master") }}
  notify:
    - recompile project
    - restart service

- name: create log directory
  become_user: "{{ daemon_user }}"
  file:
    path: "{{ log_dir }}"
    state: directory
    mode: 0755

- name: create conf directory
  become_user: "{{ daemon_user }}"
  file:
    path: "{{ eventbus_home }}/conf"
    state: directory
    mode: 0755

- name: copy application.conf
  become_user: "{{ daemon_user }}"
  copy:
    src: "{{ service_name }}.application.conf"
    dest: "{{ eventbus_home }}/conf/{{ service_name }}.application.conf"
  notify:
    - restart service

- name: copy logback.xml
  become_user: "{{ daemon_user }}"
  template:
    src: logback.j2
    dest: "{{ eventbus_home }}/conf/{{ service_name }}.logback.xml"
    mode: 0664
  notify:
    - restart service

- name: create service unit
  become: true
  template:
    src: service.j2
    dest: /lib/systemd/system/eventbus-{{ service_name }}.service
    mode: 0644
  notify:
    - reload service
    - restart service

- name: start service
  become: true
  systemd:
    name: eventbus-{{ service_name }}
    state: started