---
- name: clone or update repository
  become_user: "{{ daemon_user }}"
  git:
    repo=https://github.com/thenetcircle/event-bus.git
    dest={{ eventbus_home }}
    version={{ eventbus_version | default("master") }}
  notify:
    - recompile project
    - restart service

- name: create conf directory
  become_user: "{{ daemon_user }}"
  file:
    path: "{{ eventbus_home }}/conf"
    state: directory
    mode: 0755

- name: copy configuration
  become_user: "{{ daemon_user }}"
  copy:
    src: "{{ service_name }}.application.conf"
    dest: "{{ eventbus_home }}/conf/{{ service_name }}.application.conf"
  notify:
    - restart service

- name: create service unit
  template: src=service.j2 dest=/lib/systemd/system/eventbus-{{ service_name }}.service mode=644
  notify:
    - reload service
    - restart service